---
title: Micromine Bitcraft
hero_image: images/banner.png
description: Learn how to use your micro:bit to help (or sabotage!) Steve in Minecraft
  Pi
original_url: https://raspberrypi.org/learning/micromine-bitcraft
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Micromine bitcraft
- title: Starting Mu
- title: Connecting your micro:bit
- title: Write a program to make your micro:bit angry
- title: Buttons and pins
- title: Connect it to your Raspberry Pi
- title: Shake Steve in Minecraft
- title: 'Make blocks disappear '
- title: What next?

